name: Create new release

on:
    pull_request:
        branches:
            - master

jobs:
    release:
        name: "Stable Release"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: latest
                  prerelease: false
                  title: "Stable Release"
