name: Run tests and benchmarks

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - dev

jobs:
    testbench:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                  go-version: "^1.16.5"
            - run: go run stack
            - run: go test -v stack/stack -bench . -benchmem
